fix: getting started commands with jbang
quarkusio/quarkusio.github.io pull request #1307
Opened 2022-01-24 10:13 UTC by maxandersen

Fixing this based on https://github.com/quarkusio/quarkus/issues/22723

To test this ensure you do not have ~/.jbang/trusted-sources.json in you file system or at least no trust of maven central.

The issue here is that if you are BRAND NEW user you don't have
trusted the location quarkusio jbang catalog fetches its jars from.
i.e. you have no `~/.jbang/trusted-sources.json`

Thus if you run this command first:
`curl -Ls https://sh.jbang.dev | bash -s - app install --fresh --force quarkus@quarkusio`

jbang will ask you to trust BUT curl via pipe result in no tty being available, i.e. user
can not say/answer yes; thus until jbang 0.86 we delayed that question until
you actually try and run the installed script - but as seen in #22723
that confuses people too.

So in jbang 0.87 I made it so `jbang app install` will ask you for trust,
but it does not fix the first install as here you still don't have a tty to ask user.

Thus this PR adds explicit call for trust. Then it works for initial user too.

** If you are updating a guide, please submit your pull request to the main repository: https://github.com/quarkusio/quarkus/tree/main/docs/src/main/asciidoc **

2022-01-24 10:16 UTC, maxandersen commented
im making update to cli guide to reflect this too

2022-01-24 10:26 UTC, maxandersen commented
guide fix is at https://github.com/quarkusio/quarkus/pull/23134

2022-01-24 13:42 UTC, ebullient requested changes

2022-01-26 06:53 UTC, maxandersen commented on _includes/get-started-code-steps.html
> +curl -Ls https://sh.jbang.dev | bash -s - trust add https://repo1.maven.org/maven2/io/quarkus/quarkus-cli/
That feels like overkill. You want the same for brew tap add? 

It is effectively the same - a command to indicate you are okey installing from a specific location. 

It's intended you can copy and paste to just install.

2022-01-26 13:18 UTC, ebullient commented on _includes/get-started-code-steps.html
> +curl -Ls https://sh.jbang.dev | bash -s - trust add https://repo1.maven.org/maven2/io/quarkus/quarkus-cli/
you still just copy and paste to install. But it lets people know what they're doing and what they are trusting. You can keep it compact if you wish, but there are two commands there, and the first (as it involves trust) should be explained.

2022-03-31 18:00 UTC, merged