Add SmallRye Stork K8s service discovery post
quarkusio/quarkusio.github.io pull request #1328
Opened 2022-02-10 13:47 UTC by aureamunoz

** If you are updating a guide, please submit your pull request to the main repository: https://github.com/quarkusio/quarkus/tree/main/docs/src/main/asciidoc **

2022-02-10 14:15 UTC, cescoffier requested changes

2022-02-10 14:37 UTC, aureamunoz commented
Thanks @cescoffier .I applied your comments and stashed commits

2022-02-11 11:10 UTC, cescoffier commented
Perfect, you can remove the draft header now (and rebase).
About the publication date, I let you choose. I set the 17, I don't see any issue with your current choice.

2022-02-11 11:20 UTC, aureamunoz commented
> 

ok, thanks. Should I also stash the commits?

2022-02-11 11:57 UTC, cescoffier approved these changes

2022-02-11 11:57 UTC, merged