Add IntelliJ Quarkus Tools 1.12.0 blog post
quarkusio/quarkusio.github.io pull request #1520
Opened 2022-08-22 16:22 UTC by jeffmaury

Signed-off-by: Jeff MAURY <jmaury@redhat.com>

** If you are updating a guide, please submit your pull request to the main repository: https://github.com/quarkusio/quarkus/tree/main/docs/src/main/asciidoc **

2022-08-24 07:25 UTC, gsmet requested changes
I spotted a few things.

2022-08-24 07:25 UTC, gsmet commented on _posts/2022-08-23-intellij-quarkus-tools-1.12.0.adoc
> +This release improves the Quarkus wizard and Quarkus run experience but also align with LSP4MP 0.5.0 and quarkus-ls 0.12.1.
```suggestion
This release improves the Quarkus wizard and Quarkus run experience but also aligns with LSP4MP 0.5.0 and quarkus-ls 0.12.1.
```

2022-08-24 07:25 UTC, gsmet commented on _posts/2022-08-23-intellij-quarkus-tools-1.12.0.adoc
> +The experience has been improved so that developers can easily open Quarkus DevUI or application from Quarkus Tools.
```suggestion
The experience has been improved so that developers can easily open Quarkus Dev UI or applications from Quarkus Tools.
```

2022-08-24 07:25 UTC, gsmet commented on _posts/2022-08-23-intellij-quarkus-tools-1.12.0.adoc
> +After the application is started, a console is displayed by IntelliJ. From that console, ou can open a browser to either the Quarkus DevUI or to the Quarkus application. Right click in the console an
```suggestion
After the application is started, a console is displayed by IntelliJ. From that console, you can open a browser to either the Quarkus Dev UI or to the Quarkus application. Right click in the console and a Quarkus submenu will be displayed. It has 2 submenus: Open Dev UI and Open application. When one of these menus is selected, a new browser window is opened to the desired location.
```

2022-08-26 12:32 UTC, gastaldi commented
@jeffmaury could you take a look at the review comments proposed by @gsmet above?

2022-08-26 12:55 UTC, gsmet commented
I squashed the commits and adjusted the date. Let's wait for CI and merge.

2022-08-26 12:55 UTC, gsmet approved these changes

2022-08-26 12:56 UTC, gsmet commented
@jeffmaury if you write me a tweet, I can post it on the Quarkusio account.

2022-08-26 13:10 UTC, merged

2022-08-26 13:22 UTC, jeffmaury commented
> @jeffmaury if you write me a tweet, I can post it on the Quarkusio account.

https://twitter.com/jeffmaury/status/1563154364130533381

2022-08-26 13:24 UTC, gsmet commented
@jeffmaury thanks, retweeted