vscode-quarkus 1.13.0 release blog
quarkusio/quarkusio.github.io pull request #1684
Opened 2023-04-14 21:55 UTC by JessicaJHee

2023-04-18 13:25 UTC, JessicaJHee commented
@gsmet Do you mind taking a look at this? Thank you!

2023-04-18 14:18 UTC, gsmet requested changes
Amazing changelog. I added a few suggestions/questions. Let's try to get it merged by tonight so it gets published tomorrow.

2023-04-18 14:18 UTC, gsmet commented on _posts/2023-04-12-vscode-quarkus-1.13.0-released.adoc
> +date: 2023-04-04
Let's target for a publication tomorrow: you need to update this date and the date of the file accordingly.

2023-04-18 14:18 UTC, gsmet commented on _posts/2023-04-12-vscode-quarkus-1.13.0-released.adoc
> +https://marketplace.visualstudio.com/items?itemName=redhat.vscode-quarkus[VS Code Marketplace] & https://open-vsx.org/extension/redhat/vscode-quarkus[Open VSX].
```suggestion
https://marketplace.visualstudio.com/items?itemName=redhat.vscode-quarkus[VS Code Marketplace] and https://open-vsx.org/extension/redhat/vscode-quarkus[Open VSX].
```

2023-04-18 14:18 UTC, gsmet commented on _posts/2023-04-12-vscode-quarkus-1.13.0-released.adoc
> +The snippet completion will now take into consideration the expected content and parameters defined in the user tag. For instance, the input user tag expects the parameter name, which is generated in
> See this in action in the demo below.

Is the demo missing?

2023-04-18 14:18 UTC, gsmet commented on _posts/2023-04-12-vscode-quarkus-1.13.0-released.adoc
> +Renarde is a server-side Web Framework based on Quarkus, Qute, Hibernate, and RESTEasy Reactive. In this release, we have added support for this framework both in the Renarde template and Java file.
```suggestion
Renarde is a server-side Web Framework based on Quarkus, Qute, Hibernate ORM, and RESTEasy Reactive. In this release, we have added support for this framework both in the Renarde template and Java file.
```

2023-04-18 15:31 UTC, gsmet commented on _posts/2023-04-12-vscode-quarkus-1.13.0-released.adoc
> +date: 2023-04-19
As mentioned, you also need to rename the file. Apart from that, it looks good.

2023-04-18 15:37 UTC, gsmet approved these changes

2023-04-18 15:44 UTC, merged

2023-04-19 11:27 UTC, gsmet commented
@JessicaJHee I'll be happy to tweet something about it if you can write a tweet (or retweet something if you already have posted one)

2023-04-19 15:07 UTC, JessicaJHee commented
@gsmet I've made a tweet here: https://twitter.com/JessicaJjhe/status/1648704525409169409?s=20

Thanks very much!