Improve landing page mobile responsiveness
quarkusio/quarkusio.github.io pull request #1864
Opened 2024-01-04 02:58 UTC by bbambozzi

**Fixes**
-  Fixes #1863, removing the text overflow in mobile screens.

**Enhancements**
- Adds more media queries for a smoother mobile presentation.

2024-01-04 16:36 UTC, insectengine requested changes
Nice work! 

I'd on suggest matching the line-height to the font size for consistency in experience.

< 1024px : 5rem/5rem
< 768px : 5rem/5rem
< 550px : 3.8rem/3.8rem
< 425px : 3rem/3rem
< 375px : 2.8rem/2.8rem
<320ps : 2.5rem/2.5rem

2024-01-04 19:13 UTC, insectengine approved these changes

2024-01-15 17:07 UTC, gsmet approved these changes

2024-01-15 17:07 UTC, merged

2024-01-15 17:07 UTC, gsmet commented
Thanks for your contribution!