Add post on Jlama integration
quarkusio/quarkusio.github.io pull request #2182
Opened 2024-11-29 10:08 UTC by mariofusco

@cescoffier @geoand @maxandersen please review.

2024-11-29 12:05 UTC, geoand commented on _posts/2024-11-29-quarkus-jlama.adoc
> +In essence Jlama makes it possible to serve a LLM in Java, eventually directly embedded in the same JVM running your Java application, but why could this be useful? Actually this is desirable in many
```suggestion
In essence Jlama makes it possible to serve an LLM in Java, directly embedded in the same JVM running your Java application, but why could this be useful? Actually this is desirable in many use cases and presents a number of relevant advantages like the following:
```

2024-11-29 12:07 UTC, geoand commented on _posts/2024-11-29-quarkus-jlama.adoc
> +The only thing that needs to be remarked here is that, differently from all other LLM inference engine integrations, this doesn’t require any remote call to an external service, but performs the LLM
Do we really need to say this again?

2024-11-29 12:08 UTC, geoand commented on _posts/2024-11-29-quarkus-jlama.adoc
> +== The site summarizer: a pure Java LLM-based application
Perhaps this should also have some information about how we run it? 

I know the information is in the README, but would it not make sense to have a summary here too?

2024-11-29 13:46 UTC, mariofusco commented
@geoand Thanks for your feedback. I've incorporated all your suggestions, please review again.

2024-11-29 13:49 UTC, geoand approved these changes
Looks great!

2024-12-01 08:09 UTC, cescoffier requested changes
It’s fantastic! I’ve made a few minor comments. 

I’m wondering if attaching a recording of the demonstration would not bring more awareness.

2024-12-01 08:09 UTC, cescoffier commented on _posts/2024-11-29-quarkus-jlama.adoc
> +. *Security/Portability/Performances*: Performing the model inference in the same JVM instance that is run the application that is using it, eliminates the need of interacting with the LLM only throu
In term of resilience patterns, you do not win much. Maybe you avoid circuit breakers, but timeout and bulkhead will still be super useful.

I believe the bigger benefit is the security:

- no leak of private data
- can enforce user authorization at a much finer grain

2024-12-01 08:09 UTC, cescoffier commented on _posts/2024-11-29-quarkus-jlama.adoc
> +. *Legacy support*: The former point will be especially beneficial for legacy users, still running monolithic applications, who in this way will be also able to include LLM-based capabilities in thos
I would not associate legacy and monolith.

2024-12-01 08:09 UTC, cescoffier commented on _posts/2024-11-29-quarkus-jlama.adoc
> +. Distribution: Having the possibility to run LLM inference embedded in the same Java process will also make it possible to include the model itself into the same fat jar of the application using it
Application package instead of fat jar?

2024-12-01 08:09 UTC, cescoffier commented on _posts/2024-11-29-quarkus-jlama.adoc
> +. *Similar lifecycle between model and app*: There can be use cases where the model and the application using it have the same lifecycle, so that the development of a new feature in the application a
That’s for me the BIG WIN. As we now know, prompts are very dependent on the model. If the model gets updated even through fine-tuning, your prompt may need to be replaced. A single lifecycle avoids this, covers testinfs, versioning, improves traceability… 

I would move this item up or highlight it more.

2024-12-03 17:09 UTC, mariofusco commented
@cescoffier I also added a [video](https://www.youtube.com/watch?v=z7l1oGhWI40) to demonstrate how the application works. I believe this is ready to be merged now, please give it a final review.

2024-12-03 17:30 UTC, cescoffier commented on _posts/2024-11-29-quarkus-jlama.adoc
> +date: 2024-11-29
@mariofusco can you update the date and then we are good to go.

Without it may appear behind some other posts.

2024-12-03 17:30 UTC, cescoffier approved these changes

2024-12-03 17:35 UTC, cescoffier commented
The video is great! Love the sound of the fan :-)

2024-12-03 17:41 UTC, geoand approved these changes

2024-12-03 17:59 UTC, mariofusco commented
> The video is great! Love the sound of the fan :-)

I had to speed up the part when it does the download of the model and that made the noise even worse :smile:

2024-12-04 15:33 UTC, mariofusco commented
Any reason why we are holding this?

2024-12-04 15:53 UTC, geoand commented
Yeah, we forgot about it 😁

2024-12-04 15:53 UTC, merged