Blog post about concurrent uni in Mutiny
quarkusio/quarkusio.github.io pull request #739
Opened 2020-09-18 13:50 UTC by cescoffier

** If you are updating a guide, please submit your pull request to the main repository: https://github.com/quarkusio/quarkus/tree/master/docs/src/main/asciidoc **

2020-09-18 13:58 UTC, jponge requested changes
Typo :-)

2020-09-18 13:58 UTC, jponge commented on _posts/2020-09-29-mutiny-concurrent-uni.adoc
> +This user wanted to call two microservices _in parrallel_, and when both results are received, join them and continue the processing.
parallel

2020-09-18 13:58 UTC, kenfinnigan requested changes

2020-09-18 13:58 UTC, kenfinnigan commented on _posts/2020-09-29-mutiny-concurrent-uni.adoc
> +This user wanted to call two microservices _in parrallel_, and when both results are received, join them and continue the processing.
s/parrallel/parallel

2020-09-18 13:58 UTC, kenfinnigan commented on _posts/2020-09-29-mutiny-concurrent-uni.adoc
> +While both services a similar, the structure of the response differs a little bit.
s/services a/services are

2020-09-18 13:58 UTC, kenfinnigan commented on _posts/2020-09-29-mutiny-concurrent-uni.adoc
> +So the requests are emitted, and the services and invoked concurrently.
s/and invoked/are invoked

2020-09-18 13:58 UTC, kenfinnigan commented on _posts/2020-09-29-mutiny-concurrent-uni.adoc
> +Just creates the `Unis` representing the services or the asynchronous action you want to achieve and combine them using `Uni.combine().all()`
s/creates/create

2020-09-25 12:47 UTC, cescoffier commented
@kenfinnigan anything else to add?

2020-09-25 13:16 UTC, kenfinnigan approved these changes
sorry!

2020-09-25 13:23 UTC, merged