Replaces Travis with GitHub Actions
quarkusio/quarkusio.github.io pull request #791
Opened 2020-11-12 15:29 UTC by gastaldi

This removes the Travis descriptor and builds using GitHub actions and builds daily

2020-11-12 16:28 UTC, maxandersen requested changes

2020-11-12 16:31 UTC, gastaldi commented on package.json
> +{
Because the `afc163/surge-preview@v1` action requires it when building. I haven't tried one thing, let me check

2020-11-12 16:34 UTC, gastaldi commented on package.json
> +{
Found a solution to not require it anymore and updated the PR

2020-11-12 16:39 UTC, gastaldi commented on .github/workflows/deploy.yml
> +name: Build and deploy to GitHub Pages
IMHO I don't think it's worth the trouble of having 2 CIs (and consequently 2 build scripts) for a single task. 

It's highly likely that the time that Travis takes to build the master branch (due to the resource limits imposed) would take longer than the time it takes the GH Action to execute (even in high load scenarios). 

So I'm -1 on that.

2020-11-12 16:41 UTC, gsmet commented on .github/workflows/deploy.yml
> +name: Build and deploy to GitHub Pages
Considering the issue we have with Travis, I think it's worth a try.

But we might have to revert this if it ends up being impractical.

2020-11-12 16:42 UTC, gastaldi commented on .github/workflows/deploy.yml
> +name: Build and deploy to GitHub Pages
In the worst case scenario you can always run the build locally :wink:

2020-11-12 18:33 UTC, gastaldi commented on .github/workflows/deploy.yml
> +name: Build and deploy to GitHub Pages
I added instructions on how to deploy to GitHub pages locally if you ever need to

2020-11-13 09:49 UTC, gsmet commented
OK, let's try this and see how it goes! Thanks!

2020-11-13 09:49 UTC, merged